customLibraries: null
name: '[dev] Simple Workflow'
setupScripts:
  object:
    python:
      object:
        codeString: ''
    javascript:
      object:
        codeString: |-
          // lodash
          /* Edit library variable below */

          const _ = require('lodash')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */


          // numbro
          /* Edit library variable below */

          const numbro = require('numbro')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */


          // papaparse
          /* Edit library variable below */

          const Papa = require('papaparse')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */


          // moment-timezone
          /* Edit library variable below */

          const moment = require('moment-timezone')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */


          // uuid
          /* Edit library variable below */

          const uuid = require('uuid')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
triggerWebhooks:
  array:
    - object:
        name: webhook1
        inputSchema:
          object:
            properties:
              array: []
version: 43.0.9
workflowId: fadec0de-badb-ea75-cafe-000000000002
description: null
workflowTemplate:
  appTesting:
    object:
      testSuites:
        array: []
      tests:
        object: {}
  version: 3.113.0
