<PlaygroundQuery
  id="Untitled"
  adhocResourceType="RESTQuery"
  data={null}
  resourceType={null}
>
  <RESTQuery
    allowedGroupIds={[]}
    allowedGroups={[]}
    events={[]}
    importedQueryDefaults={{}}
    importedQueryInputs={{}}
    privateParams={[]}
    queryTimeout="100000"
    retoolVersion="3.93.0"
    watchedParams={[]}
  />
</PlaygroundQuery>
